### PR TITLE
Add contribution guidelines and share IntelliJ run configurations for `runJosm` and `dist` tasks

### LINKED ISSUE #27: Document process of setting up the project for development
updating the Readme file with Supplemental information for JOSM .

### PR DESCRIPTION
**Pull request by floscher**
Fixes #27, this adds contribution guidelines for contributing code and translations.

See here for the `CONTRIBUTING.md` file: https://github.com/JOSM/pt_assistant/blob/contribution_guidelines/docs/CONTRIBUTING.md

### CODE REVIEW

**Comment by floscher** [comment]
@sonukushwaha403 does this help?

**Comment by floscher** [comment]
@sonukushwaha403 does this help?

**Review by sonukushwaha403 — COMMENTED** [review]
Seems well n good

**Review by sonukushwaha403 — APPROVED** [review]

**Review by PolyglotOpenstreetmap — APPROVED** [review]
This looks great! Thanks @floscher for documenting it and @sonukushwaha403 for raising the issue.

**Pull request merged**
