### PR TITLE
stopToWays fix

### PR DESCRIPTION
**Pull request by sudhanshu2**
I am currently testing it, but I believe this fix should work.

### CODE REVIEW

**Review by michaelzangl — CHANGES_REQUESTED** [review]
Avoid static

**Comment by sudhanshu2** [comment]
> Avoid static

@michaelzangl I removed static. Should I remove it from all of the code?

**Comment by michaelzangl** [comment]
In most cases, things will break when doing this ;-)

**Comment by sudhanshu2** [comment]
Oh I see. I will currently work on refactoring the code and understanding the workflow then before fixing this issue!

**Pull request closed without merging**
