### PR TITLE
Create an AddNearestWayAction

### PR DESCRIPTION
**Pull request by floscher**
@PolyglotOpenstreetmap @sudhanshu2 @michaelzangl I stumbled across this commit from march that added the new AddNearestWayAction: https://github.com/Fishysituation/pt_assistant/commit/a146a8d797adb97adbb3cfe1004d12678b1c2ba2 (I guess as part of a GSoC application)

If such an action would still be useful, we could merge this so it wasn't for nothing. In an effort to also re-familiarize myself with some intricacies of JOSM programming, I reworked it a bit, so the basic functionality is working.

It currently finds all nodes with role "stop" in the route relation and adds the ways connected to this node to the relation.

Issues that still exist:
* the icon is borrowed from the routing helper, would need a different one
* there's no checks on what the connected ways are (ideally only highways/railways should be added)
* the ways are added at the end of the relation, not where they would fit in best
* only ways of which the "stop" node is part of are added, ways that are just near the stop position are not accounted for

### CODE REVIEW

**Comment by PolyglotOpenstreetmap** [comment]
This is not how that was supposed to work. Other candidates have made
better implementations.

Jo

**Comment by floscher** [comment]
@PolyglotOpenstreetmap ok, I'll close it then. Are these better implementations somewhere in a state that could be merged?

**Comment by PolyglotOpenstreetmap** [comment]
I could ask the candidates that didn't make it, if they want to share their
code. I only have it as JAR-files. But it would probably be better to
reimplement it from scratch.

It's not really complicated after all. Make a loop over all stops in the
route relation and ask PT_Assistant what way is adjacent to it. Last summer
there was code developed for this. It's under data. You can ask which way
is adjacent for a stop and you can ask which stops are next to a way and
even on which side of the way they are. This allows the validator to warn
the user about stops that can't be served, for example.

A good implementation would indeed add the ways where they should be added
logically, inserting them between other ways (not entirely trivial, simply
adding them at the end was a lot simpler).

I also think this doesn't deserve a separate button, it can simply be added
as a 'precursor' to the routing helper. The routing helper is not capable
of working, if there are no ways in the route relation. It also become a
lot more effective/efficient if there are more ways in the route relation,
than if there is only the first and the last.

One other thing that might be helpful is to check whether there are T's in
the route, i.e. a way's first or last node is another way's middle node. In
that case it's likely that the way needs to be split on that middle node
(and only the part kept that is adjacent to a stop of the route relation).
Not sure if it would be best to ask the user, or if it would be OK to
simply split the way at that point and move on.

Jo

**Comment by floscher** [comment]
No need then to ask them for the code. I just saw that branch laying around and wanted to make sure there isn't something useful that's overlooked.

Indeed there are several things that need to be accounted for and I think too that it would be better if it were integrated into the routing helper. But that can be discussed when this feature will be (re)implemented…

**Pull request closed without merging**
