### PR TITLE
Merge with plugin `public_transport_layer`

### PR DESCRIPTION
**Pull request by floscher**
This pull request takes the relatively small JOSM plugin [`public_transport_layer`](https://josm.openstreetmap.de/wiki/Help/Plugin/PublicTransportLayer) and adds its classes (two `JosmAction`s) to `pt_assistant`.

There are so many commits in this pull request, because that's the commit history of the other plugin.
The [relevant commits](https://github.com/JOSM/pt_assistant/pull/6/files/dbe23b26e77507b504c1488be09ea45e25f89859..2feead295af86089e20cf15ad9ac4c2368de6d42) that do the merge, are:
* ff5f025 Converts the `*.lang` files to `*.po` files, so they can be merged with the ones from `pt_assistant`, moves the Java classes to a subpackage of `org.openstreetmap.josm.plugins`
* 2feead2 the actual merge, drops the `Plugin` class of `public_transport_layer`, merges translations and other files (Eclipse settings, Ant/Gradle properties)

The new classes should be merged over time with existing similar classes from `pt_assistant`. Especially `PublicTransportLayer`, since there are now two kinds of public transport layer.

I hope that's ok with you @biswesh456 and @simon04 as the maintainers of the plugins in question :wink: .

Please, when having reviewed the PR, don't simply merge it with GitHub's UI. I'd simply push this branch to master instead of merging it, to keep the history cleaner (I guess GitHub's "rebase merge" would do the same, but I'm not sure).

### CODE REVIEW

**Comment by PolyglotOpenstreetmap** [comment]
I have often wondered what this plugin did. Up till now I hadn't been able to figure it out. It's only after downloading some data in Germany and switching off the data layer that I can make it display something.

So it draws straight lines between stop_position nodes. As my bus route relations don't contain stop_position nodes, it's no wonder that I didn't see anything happen before. The plugin should either additionally draw lines to the platform nodes or the center points of platforms drawn as way or closedway. Or it should try to figure out which stop_position and platform belong together and compute a center point between them, in case both are added to the route relations,

I think the lines are a bit thin, almost invisible.

I do like the right mouse button menu on the layer (but I wouldn't have figured out it was possible to do that without reading the documentation).

If the layers will be merged into one, we will need a way for the user to decide what to show.

Maybe we should rename it to Routes Layer as PT_Assistant also highlights bicycle and foot routes.

When the user selects the Graph View, would it make sense to hide the data layers automatically?

The standard view mode of PT_Assistant is

* Highlight active route(s)
  (Either the selected ones, or the one that has a relation editor window with focus)

These would have to be added to the right mouse menu option:

* Show direct connections between stops as graph
* Show route bundles
  (like a metro map, coloured lines side by side)
* Show stops and ways in between as colour gradient along the rainbow
  (the idea here is to be able to see that the order is correct)

The 2 last options don't exist (except in my dreams :-) )

**Comment by PolyglotOpenstreetmap** [comment]
Regarding the 'original' public_transport plugin, I would be very surprised anyone still uses it. Its best feature was adding bus stops after drawing adding all the ways, but that too is rather error prone. I think we can silently drop it and see if anyone complains. I found it difficult to work with.

I will have a look at the CustomizePublicTransportStop plugin. OK, looked at it. It does something that I deem unnecessary. From a platform node it finds the nearest point on the adjacent highway and creates a stop_position node, which it then ties to the platform using a stop_area relation. In the process it duplicates all the data of the bus stop to the stop position node and the stop_area relation.

I don't have very strong opinions about most things, but needlessly duplicating data makes maintaining it harder to do, so as far as I'm concerned that's a big no no.

Having said that, it would probably be relatively simple to merge the functionaltiy in case there are people who do see a need for it. The menu option should be moved from tools to public_transport in that case.

Jo

**Comment by floscher** [comment]
I think I'll move forward with this merge.

@don-vip What would be the steps to remove the plugin `public_transport_layer` and directing its users to `pt_assistant`?

Regarding the other public transport plugins, thank you @PolyglotOpenstreetmap for your view of those.

**Comment by stoecker** [comment]
> What would be the steps to remove the plugin public_transport_layer and directing its users to pt_assistant?

If the features are copied and the replace is finished open a ticket for core. We then add the plugin to the "deprecated" list with a note that it is replaced by another one.

Please make sure that it is acceptable to users. There shouldn't be a majority of users yelling "but the old plugin is still better" or the like...

**Comment by don-vip** [comment]
I never used the plugin. Simon knows it better :) But it's a good thing to merge similar plugins, we have too many of them and it's unmaintainable.

**Comment by floscher** [comment]
The merge is now completed. For removal of the `public_transport_layer` plugin and redirecting users to `pt_assistant`, I created https://josm.openstreetmap.de/ticket/16961

**Comment by PolyglotOpenstreetmap** [comment]
Hi @simon04 We'll need to look into how to go about merging the 2 layers, or would you keep them as separate layers? Also, did you see my message about how it only draws lines between stop_position nodes? In PT_Assistant Darya created a PT_Stop object under data, maybe it would be possible to calculate a center point in that and use that instead?

**Pull request merged**
