### PR TITLE
Route master diagram

### PR DESCRIPTION
**Pull request by michaelzangl**
Enhances the relation edit dialog

**Relation type=route**
* Allows adding to a route master (if not present)
  * Allows to download all route masters in the area
* Displays all routes in the route master as diagram.
  * If no route master is present, only current route is displayed
* Displays all stops of that route
  * Respects all role members with stop / plaftform roles.
  * Allows to start editing them if they are a stop_area
  * Allows to zoom to a stop node
* Colors stops according to exit (red), entry (green) and normal (black)
  * **TODO**: Use icons for this, add tooltips
* Colors main line according to 'colour' tag
* **TODO**: Add tooltip with the platform (name) the route stops at
* Allows to download all related route relations + their stops.

**Relation type=route_master**
* Same diagram as for type=route
* Allows to download all child route relations + their stops.

**Relation type=stop_area**
* Displays a diagram of the lines passing there and their next/previous stop(s)
 * Provides the ability to start editing those routes + the other stops
* Display the vicinity of the stop area
 * Background geometry is displayed in dark gray
 * Light colors indicate public transport infrastructure like platforms / routes.
 * Items belonging to the stop area are colored blue
 * Clicking on some items allows adding / removing them
    * Currently: platform (way only), stop position.
    * **TODO**: Make a list of all the things that should belong to a stop area and make them interactive that way
    * **TODO**: The mapcss style might need some additional work.

**Other**
* Menu item to create a stop area of some selected primitives.

Did not test it much, may throw errors in many corner cases (e.g. missing tags)

Bildschirmfoto von 2020-11-26 22-44-59

Bildschirmfoto von 2020-11-29 23-33-41
Bildschirmfoto von 2020-11-29 23-35-01

### CODE REVIEW

**Comment by michaelzangl** [comment]
@PolyglotOpenstreetmap 
Can you send me an overpass query that given a *route master relation id*, downloads:
* All routes
* The stops for each route
* The ways for each route
* The stop areas for each stop

Can you send me an overpass query that given a *route relation id*, downloads:
* The corresponding route master
* Everything from the master (see above)

**Comment by PolyglotOpenstreetmap** [comment]
> @PolyglotOpenstreetmap
> Can you send me an overpass query that given a _route master relation id_, downloads:
> 
> * All routes
> * The stops for each route
> * The ways for each route
> * The stop areas for each stop
> 
> Can you send me an overpass query that given a _route relation id_, downloads:
> 
> * The corresponding route master
> * Everything from the master (see above)

Hi Michael,

After some fiddling on Overpass Turbo, I came up with the following:

https://overpass-turbo.eu/s/10C5

relation(3298880)->.routeMaster;
.routeMaster >> ->.allRoutesOfRouteMaster;

nw[highway=bus_stop].allRoutesOfRouteMaster -> .bus_stops;
.bus_stops << -> .bus_stop_parents;
rel.bus_stop_parents["public_transport"="stop_area"] -> .stop_areas;
(
.allRoutesOfRouteMaster;
.bus_stops;
.stop_areas;
._ >;
);
out meta;

For getting the route_master parents of a route relation: 

relation(1708566)->.route;
.route << -> .parents;
rel.parents["type"="route_master"] -> .routeMaster;
(
.routeMaster;
);
out meta;

And all combined: 

https://overpass-turbo.eu/s/10C8

relation(1708566)->.route;
.route << -> .parents;
rel.parents["type"="route_master"] -> .routeMaster;

.routeMaster >> ->.allRoutesOfRouteMaster;

nw[highway=bus_stop].allRoutesOfRouteMaster -> .bus_stops;
.bus_stops << -> .bus_stop_parents;
rel.bus_stop_parents["public_transport"="stop_area"] -> .stop_areas;
(
.allRoutesOfRouteMaster;
.bus_stops;
.stop_areas;
._ >;
);
out meta;

It takes longer than I had expected to execute. I don't see how I could filter the result while asking for recursive parents, so the filtering happens one step later.

**Review by PolyglotOpenstreetmap — APPROVED** [review]
This is great functionality. It doesn't work on the PT relations I mapped, because up till now I hadn't mapped all the stop_area relations and because the stop_area relations that I did map only contain the stop primitives for one direction of travel/side of the road.. I then had a 'hierarchy' of another stop_area or stop_area_group relation that contained stop_area relations. At bus stations, I had a stop_area_group for all the stop_area relations of that station. And at combined bus/metro/train stations, I have a third level that groups those.
I think somewhere along the line I stopped using stop_area_group and simply made a 'pyramid' of stop_area relations...

**Comment by michaelzangl** [comment]
@PolyglotOpenstreetmap Platforms will be coming ;-)

I think that whole PT scheme is very difficult to handle because it is so ambiguous.

The ways are fine - finding the way the PT runs on is easy, they are ordered in the relation. Forward/Backward information is missing but can be inferred in most cases.

The stop positions are difficult. Because we may have platforms or stops. Or both.  Both the platform and the stop position are in the relation. But in no special order. By the relation itself, I cannot find out if someone mapped a stop with corresponding platform or if someone mapped a stop, followed by a platform. Therefore, I need a stop area relation. Mapping only one direction there may cause problems

**Simple example**
This is a nice simple example of a station:
https://www.openstreetmap.org/relation/4086031
And this is the tram line stopping at that station:
https://www.openstreetmap.org/relation/176700#map=19/49.00165/8.37831

Matching is simple there: stop and platform belong to the same stop_area. So I can match them and remove the duplicate entries. 

**More difficult example**
Station:
https://www.openstreetmap.org/relation/140180
Bus line:
https://www.openstreetmap.org/relation/405216#map=18/48.99472/8.40048

Here, the bus stops twice at the station (even at the same platform). In the timetable, this is only one stop. In the graph, I would also mark it as one stop (it currently is not, because the nodes 3538953109 is not a member of the stop_area but it should be).

You see, since everything is marked as a stop area, I have no problem with the bus stopping twice at platform D. Because both stop positions belong to the station. I can give both the information that the bus stops at platform D and the information where it stops.

The wiki was very clear on what to include in a stop area:
https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area
> A stop area for a simple bus stop with buses in both directions would consist of two waiting areas or shelters

You may not have a stop_area as child of a stop_area, since that is [not allowed](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area#Members)

**Comment by michaelzangl** [comment]
Bildschirmfoto von 2020-11-27 14-48-47

(Color should be blue, but since I am currently abusing :selected as marker of the current relation, JOSM colors it in the selected relation color)

**Comment by michaelzangl** [comment]
Colors are fixed, interaction is possible (currently only supports adding/removing stop positions and platforms)

Bildschirmfoto von 2020-11-27 19-10-47

**Comment by michaelzangl** [comment]
@PolyglotOpenstreetmap If you want to, you can try the download scripts now.

I also added a download script to download all master routes in the area around the route. Currently only available if you have a route without a route master, when clicking on the 'Add to route master' button.

Do you have time for a hangout / … so that we can discuss more features? What I can think of is:
* Select multiple items on the map, then 'Create stop area relation'
* Allow the route master download form a more centralized place
* In the route tab, show numbers of other routes stopping at that stop + ability to switch to their routes
* Add a new 'Map' tab to the relation with `type=route` (does not need PT route then, can be all routes) and display a highlighted View of the route, with a minimalistic style (just the route in e.g. blue, other routes in white, usable roads/rails in gray, then all stops as dots, stop index next to the stop)

**Comment by PolyglotOpenstreetmap** [comment]
hi @michaelzangl 

I have time for a hangout tomorrow morning until noon, or after 16h in the evening.

those little maps in the relation editor are wonderful!

Jo

**Comment by michaelzangl** [comment]
Stop area groups are a bit more complicated because of the way rendering currently works - I will do a separate PR for them later.

**Comment by michaelzangl** [comment]
Invalid stop area members are now displayed red. I added a legend to that view as well, so that users know.
Bildschirmfoto von 2020-11-30 17-59-04

**Comment by michaelzangl** [comment]
Stop area routes panel should be much more useful now.

Bildschirmfoto von 2020-12-01 16-01-43

**Comment by PolyglotOpenstreetmap** [comment]
yes, that looks so much better for those stops served by many lines! Did you push that commit? I'm not seeing it when I update. Would you have time for a hangout tomorrow evening?

**Comment by PolyglotOpenstreetmap** [comment]
Yes, a big improvement! I succeeded in breaking it by removing the members, not saving, and then going to the Vicinity tab. It causes a NullPointerException

hread: AWT-EventQueue-0 (18) of main
java.lang.NullPointerException
	at org.openstreetmap.josm.gui.NavigatableComponent.zoomTo(NavigatableComponent.java:843)
	at org.openstreetmap.josm.plugins.pt_assistant.gui.utils.AbstractVicinityPanel.zoomToEditorRelation(AbstractVicinityPanel.java:183)
	at org.openstreetmap.josm.plugins.pt_assistant.gui.stoparea.StopVicinityPanel.doInitialZoom(StopVicinityPanel.java:211)
	at org.openstreetmap.josm.plugins.pt_assistant.gui.utils.AbstractVicinityPanel$2.prepareToDraw(AbstractVicinityPanel.java:96)
	at org.openstreetmap.josm.gui.MapView.paint(MapView.java:479)

It also happens when I do save in the relation editor.

**Comment by michaelzangl** [comment]
Stop index is now highlighted in member view, colored red if too far away from way.
Member list
Map view
After deleting members
After deleting members

**Comment by michaelzangl** [comment]
Moved to separate plugin:
https://github.com/michaelzangl/josm-visualize-routes

**Pull request closed without merging**
